name: 'contracts'

env:
  NETWORK_NAME: conduit
  PLUGIN_REPO_FACTORY_ADDRESS: '0x1bA8bf087d54F03781C735E14f7a6655E1A876aF'
  PLUGIN_REPO_REGISTRY_ADDRESS: '0xF0e1405b91c113CeC351A7ce038442C28353135A'
  PLUGIN_SETUP_PROCESSOR_ADDRESS: '0xfcC0Aba63c1F1f887099EAB0d1A624A5B7A82Fc2'
  DEPLOYMENT_RPC_ENDPOINT: ${{ secrets.DEPLOYMENT_RPC_ENDPOINT }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  working-directory: packages/contracts

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contracts-*.yml'

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 18

      - name: 'Install the dependencies'
        run: 'yarn install'

      - name: 'Build the contracts'
        run: 'yarn build'
        working-directory: packages/contracts

      - name: 'Test the contracts and generate the coverage report'
        run: 'yarn coverage'
        working-directory: packages/contracts
